### PR TITLE
ENH: add QuiverCD to support quiver exports

### PR DESCRIPTION
**Pull request by jpfairbanks**
Addresses #3 by embedding the quiver style file into the preamble.

### CODE REVIEW

**Comment by mehalter** [comment]
@jpfairbanks instead of making a separate method like `QuiverCD`, I think it makes more sense for us to make a new module of preset preambles. Then it can be easily extended by users through string manipulation and you get a syntax like

```
using TikzCDs
using TikzCDs: preambles

tp = TikzCD(data, preamble=preambles.Quiver, options="scale=0.25")
```

What do you think? I'm just looking for a more general approach that can be extended to supporting other commutative diagrams styles that might come up down the line instead of changing the API to interact with the package.

**Comment by mehalter** [comment]
@jpfairbanks let me know what you think of that and if you would want me to migrate what you have done here into another PR and do the final steps to getting it merged. I'm happy to help

**Comment by jpfairbanks** [comment]
Are there any other CD building tools besides quiver? I think that quiver is big enough that it is worth having explicit support for it. I wouldn't mind passing an argument to the TikzCD function rather than a separate api function. Given the high cost to develop a TikzCD building tool, I don't think we need to worry about a proliferation of these tools.

Maybe we call them Styles and you pass a struct like Styles.Quiver for the style that you want? I could see you wanting to do more than just append to the preamble when using a different style.

**Comment by mehalter** [comment]
Yeah `Styles` I think would be a good way to do it.

**Comment by jpfairbanks** [comment]
Do you want to take a crack at it on this PR?

**Comment by mehalter** [comment]
Yeah I can do that, have you allowed editing of the branch?

**Comment by mehalter** [comment]
Moving development to `styles` branch with PR #5

**Pull request closed without merging**
